// Pure HTML → Angular template converter.
//
// Goal: translate Tailwind-friendly HTML generated by the variant stream into
// an Angular 17+ standalone component scaffold that uses the new built-in
// control-flow syntax (@for / @if). The converter is intentionally heuristic:
// it does not aim for total fidelity, but for a readable, reviewable bridge.
//
// Every transform that fires is tagged by name in `AppliedHeuristic`. The
// emitted component TS file opens with a short summary listing which
// heuristics fired on the input so a reviewer can see *why* the output looks
// the way it does without having to re-run the converter.

export type AppliedHeuristic =
  | "onclick-to-click"
  | "onchange-to-change"
  | "oninput-to-input"
  | "list-to-for"
  | "data-if-to-if"
  | "data-show-to-if"
  | "data-model-to-ngmodel"
  | "data-bind-to-property"
  | "checkbox-to-checked"
  | "form-reactive-hint";

export interface AngularConversionOptions {
  componentName?: string;
  useSignals?: boolean;
}

export interface AngularConversionResult {
  template: string;
  componentTs: string;
  imports: string[];
  /**
   * Extra annotations that the caller can include in the handoff prompt.
   * Present when the converter detects Angular-specific integration work
   * that cannot be expressed in the template alone (e.g. FormsModule
   * imports, reactive-form scaffolding).
   */
  followUps: string[];
}

// --- AST types -------------------------------------------------------------

type AttrPair = [string, string | null];

interface ElementNode {
  type: "element";
  tag: string;
  attrs: AttrPair[];
  children: AstNode[];
}

interface TextNode {
  type: "text";
  text: string;
}

interface CommentNode {
  type: "comment";
  text: string;
}

type AstNode = ElementNode | TextNode | CommentNode;

// Elements that never have children or closing tags in HTML5.
const VOID_TAGS = new Set([
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]);

// --- Tokenizer -------------------------------------------------------------

type Token =
  | {
      kind: "open";
      tag: string;
      attrs: AttrPair[];
      selfClosing: boolean;
    }
  | { kind: "close"; tag: string }
  | { kind: "text"; text: string }
  | { kind: "comment"; text: string };

function tokenize(html: string): Token[] {
  const tokens: Token[] = [];
  let i = 0;
  while (i < html.length) {
    if (html[i] === "<") {
      if (html.startsWith("<!--", i)) {
        const end = html.indexOf("-->", i + 4);
        const close = end === -1 ? html.length : end;
        tokens.push({ kind: "comment", text: html.slice(i + 4, close) });
        i = end === -1 ? html.length : end + 3;
        continue;
      }
      if (html[i + 1] === "!") {
        // DOCTYPE / CDATA — skip to `>`
        const close = html.indexOf(">", i);
        i = close === -1 ? html.length : close + 1;
        continue;
      }
      if (html[i + 1] === "/") {
        const close = html.indexOf(">", i);
        const tag = html
          .slice(i + 2, close === -1 ? html.length : close)
          .trim()
          .toLowerCase();
        tokens.push({ kind: "close", tag });
        i = close === -1 ? html.length : close + 1;
        continue;
      }
      const close = findTagClose(html, i);
      const raw = html.slice(i + 1, close);
      const parsed = parseOpenTag(raw);
      tokens.push({
        kind: "open",
        tag: parsed.tag,
        attrs: parsed.attrs,
        selfClosing: parsed.selfClosing,
      });
      i = close + 1;
    } else {
      const next = html.indexOf("<", i);
      const end = next === -1 ? html.length : next;
      const text = html.slice(i, end);
      if (text.length > 0) tokens.push({ kind: "text", text });
      i = end;
    }
  }
  return tokens;
}

function findTagClose(html: string, start: number): number {
  let i = start + 1;
  let inQuote: string | null = null;
  while (i < html.length) {
    const ch = html[i];
    if (inQuote) {
      if (ch === inQuote) inQuote = null;
    } else if (ch === '"' || ch === "'") {
      inQuote = ch;
    } else if (ch === ">") {
      return i;
    }
    i++;
  }
  return html.length;
}

function parseOpenTag(raw: string): {
  tag: string;
  attrs: AttrPair[];
  selfClosing: boolean;
} {
  const trimmed = raw.trim();
  const selfClosing = trimmed.endsWith("/");
  const body = selfClosing ? trimmed.slice(0, -1).trim() : trimmed;
  const firstSpace = body.search(/\s/);
  const tag = (
    firstSpace === -1 ? body : body.slice(0, firstSpace)
  ).toLowerCase();
  const rest = firstSpace === -1 ? "" : body.slice(firstSpace + 1);
  const attrs: AttrPair[] = [];
  const attrRegex =
    /([^\s=/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g;
  let m: RegExpExecArray | null;
  while ((m = attrRegex.exec(rest)) !== null) {
    const name = m[1];
    let value: string | null;
    if (m[2] !== undefined) value = m[2];
    else if (m[3] !== undefined) value = m[3];
    else if (m[4] !== undefined) value = m[4];
    else value = null;
    attrs.push([name, value]);
  }
  return { tag, attrs, selfClosing };
}

// --- Parser ----------------------------------------------------------------

function parseHtml(html: string): AstNode[] {
  const tokens = tokenize(html);
  const roots: AstNode[] = [];
  const stack: ElementNode[] = [];

  for (const token of tokens) {
    const parent = stack.length > 0 ? stack[stack.length - 1] : null;
    const sink = parent ? parent.children : roots;

    if (token.kind === "text") {
      sink.push({ type: "text", text: token.text });
    } else if (token.kind === "comment") {
      sink.push({ type: "comment", text: token.text });
    } else if (token.kind === "open") {
      const el: ElementNode = {
        type: "element",
        tag: token.tag,
        attrs: token.attrs,
        children: [],
      };
      sink.push(el);
      const isVoid = VOID_TAGS.has(token.tag) || token.selfClosing;
      if (!isVoid) stack.push(el);
    } else if (token.kind === "close") {
      for (let i = stack.length - 1; i >= 0; i--) {
        if (stack[i].tag === token.tag) {
          stack.length = i;
          break;
        }
      }
    }
  }

  return roots;
}

// --- Transform -------------------------------------------------------------

interface TransformContext {
  applied: Set<AppliedHeuristic>;
  fields: Record<string, string>;
  fieldOrder: string[];
  methods: Set<string>;
  listCounter: { value: number };
  usesFormsModule: boolean;
  reactiveFormHint: boolean;
}

function newContext(): TransformContext {
  return {
    applied: new Set<AppliedHeuristic>(),
    fields: {},
    fieldOrder: [],
    methods: new Set<string>(),
    listCounter: { value: 0 },
    usesFormsModule: false,
    reactiveFormHint: false,
  };
}

function setField(ctx: TransformContext, name: string, value: string): void {
  if (!(name in ctx.fields)) ctx.fieldOrder.push(name);
  ctx.fields[name] = value;
}

const IDENT_RE = /^[A-Za-z_$][\w$]*$/;

function isValidIdent(name: string): boolean {
  return IDENT_RE.test(name);
}

// Marker used by transform to flag a wrapper without mutating the tree shape.
// A wrapper element with tag "__if__" and attr [expr, value] is emitted as
// `@if (value) { ... }` at serialize time.
const IF_WRAPPER_TAG = "__if__";

function transformTree(nodes: AstNode[], ctx: TransformContext): AstNode[] {
  const out: AstNode[] = [];
  for (const node of nodes) {
    if (node.type !== "element") {
      out.push(node);
      continue;
    }
    const transformed = transformElement(node, ctx);
    out.push(transformed);
  }
  return maybeFoldList(out, ctx);
}

function transformElement(
  el: ElementNode,
  ctx: TransformContext,
): AstNode {
  const newAttrs: AttrPair[] = [];
  let dataIfExpr: string | null = null;
  let dataShowExpr: string | null = null;

  if (el.tag === "form") {
    ctx.applied.add("form-reactive-hint");
    ctx.reactiveFormHint = true;
  }

  const attrMap = new Map<string, string | null>(
    el.attrs.map(([k, v]) => [k.toLowerCase(), v]),
  );
  const isCheckboxLike =
    el.tag === "input" &&
    ((attrMap.get("type") ?? "").toLowerCase() === "checkbox" ||
      (attrMap.get("type") ?? "").toLowerCase() === "radio");

  for (const [name, value] of el.attrs) {
    const lower = name.toLowerCase();
    if (lower === "onclick" && value !== null) {
      ctx.applied.add("onclick-to-click");
      registerHandlerStub(ctx, value);
      newAttrs.push(["(click)", value]);
      continue;
    }
    if (lower === "onchange" && value !== null) {
      ctx.applied.add("onchange-to-change");
      registerHandlerStub(ctx, value);
      newAttrs.push(["(change)", value]);
      continue;
    }
    if (lower === "oninput" && value !== null) {
      ctx.applied.add("oninput-to-input");
      registerHandlerStub(ctx, value);
      newAttrs.push(["(input)", value]);
      continue;
    }
    if (lower === "data-if" && value !== null) {
      dataIfExpr = value;
      registerConditionField(ctx, value);
      continue;
    }
    if (lower === "data-show" && value !== null) {
      dataShowExpr = value;
      registerConditionField(ctx, value);
      continue;
    }
    if (lower === "data-model" && value !== null && isValidIdent(value)) {
      ctx.applied.add("data-model-to-ngmodel");
      ctx.usesFormsModule = true;
      registerModelField(ctx, value, el, attrMap);
      if (isCheckboxLike) {
        ctx.applied.add("checkbox-to-checked");
        newAttrs.push(["[(ngModel)]", value]);
      } else {
        newAttrs.push(["[(ngModel)]", value]);
      }
      newAttrs.push(["name", value]);
      continue;
    }
    if (lower === "data-bind" && value !== null && isValidIdent(value)) {
      ctx.applied.add("data-bind-to-property");
      registerReadonlyField(ctx, value);
      if (isCheckboxLike) {
        ctx.applied.add("checkbox-to-checked");
        newAttrs.push(["[checked]", value]);
      } else {
        newAttrs.push(["[value]", value]);
      }
      continue;
    }
    newAttrs.push([name, value]);
  }

  const transformedChildren = transformTree(el.children, ctx);

  const transformedEl: ElementNode = {
    type: "element",
    tag: el.tag,
    attrs: newAttrs,
    children: transformedChildren,
  };

  if (dataIfExpr !== null) {
    ctx.applied.add("data-if-to-if");
    return {
      type: "element",
      tag: IF_WRAPPER_TAG,
      attrs: [["expr", dataIfExpr]],
      children: [transformedEl],
    };
  }
  if (dataShowExpr !== null) {
    ctx.applied.add("data-show-to-if");
    return {
      type: "element",
      tag: IF_WRAPPER_TAG,
      attrs: [["expr", dataShowExpr]],
      children: [transformedEl],
    };
  }
  return transformedEl;
}

function defaultForInputType(inputType: string | null | undefined): string {
  if (!inputType) return "''";
  const t = inputType.toLowerCase();
  if (t === "number" || t === "range") return "0";
  if (t === "checkbox" || t === "radio") return "false";
  return "''";
}

function registerModelField(
  ctx: TransformContext,
  name: string,
  el: ElementNode,
  attrMap: Map<string, string | null>,
): void {
  if (name in ctx.fields) return;
  if (el.tag === "input") {
    const initial = defaultForInputType(attrMap.get("type") ?? null);
    setField(ctx, name, initial);
    return;
  }
  if (el.tag === "textarea") {
    setField(ctx, name, "''");
    return;
  }
  if (el.tag === "select") {
    setField(ctx, name, "''");
    return;
  }
  setField(ctx, name, "''");
}

function registerReadonlyField(ctx: TransformContext, name: string): void {
  if (!(name in ctx.fields)) setField(ctx, name, "''");
}

function registerHandlerStub(ctx: TransformContext, expression: string): void {
  const match = expression.match(/^\s*([A-Za-z_$][\w$]*)\s*\(/);
  if (match) {
    ctx.methods.add(match[1]);
  }
}

function registerConditionField(ctx: TransformContext, expression: string): void {
  const match = expression.match(/^\s*([A-Za-z_$][\w$]*)\s*$/);
  if (match) {
    const name = match[1];
    if (!(name in ctx.fields)) {
      setField(ctx, name, "false");
    }
  }
}

// After children are transformed, look for run-length groups of same-tag
// element siblings whose inner content is plain text. Fold those groups into
// a single templated child and collect the raw labels into a data field.
function maybeFoldList(nodes: AstNode[], ctx: TransformContext): AstNode[] {
  const result: AstNode[] = [];
  let i = 0;
  while (i < nodes.length) {
    const node = nodes[i];
    if (node.type !== "element") {
      result.push(node);
      i++;
      continue;
    }
    const group = collectSameTagRun(nodes, i);
    if (
      group.length >= 2 &&
      group.every(isPlainTextLeafElement) &&
      allSignaturesEqual(group)
    ) {
      const labels = group.map((el) => extractPlainText(el));
      const fieldName = allocateListField(ctx);
      setField(ctx, fieldName, serializeStringArray(labels));
      ctx.applied.add("list-to-for");

      const first = group[0];
      const templated: ElementNode = {
        type: "element",
        tag: first.tag,
        attrs: first.attrs,
        children: [{ type: "text", text: "{{ item }}" }],
      };
      const forWrapper: ElementNode = {
        type: "element",
        tag: "__for__",
        attrs: [
          ["alias", "item"],
          ["source", fieldName],
        ],
        children: [templated],
      };
      result.push(forWrapper);
      i += group.length;
      continue;
    }
    result.push(node);
    i++;
  }
  return result;
}

function collectSameTagRun(nodes: AstNode[], start: number): ElementNode[] {
  const first = nodes[start];
  if (first.type !== "element") return [];
  const run: ElementNode[] = [first];
  for (let j = start + 1; j < nodes.length; j++) {
    const next = nodes[j];
    if (next.type === "text" && next.text.trim() === "") continue;
    if (next.type !== "element" || next.tag !== first.tag) break;
    run.push(next);
  }
  return run;
}

function isPlainTextLeafElement(el: ElementNode): boolean {
  return el.children.every((child) => child.type === "text");
}

function allSignaturesEqual(els: ElementNode[]): boolean {
  const signature = (el: ElementNode): string =>
    el.tag +
    "|" +
    el.attrs
      .map(([k, v]) => `${k}=${v ?? ""}`)
      .sort()
      .join(";");
  const first = signature(els[0]);
  return els.every((el) => signature(el) === first);
}

function extractPlainText(el: ElementNode): string {
  return el.children
    .filter((c): c is TextNode => c.type === "text")
    .map((c) => c.text.trim())
    .join(" ")
    .trim();
}

function allocateListField(ctx: TransformContext): string {
  const n = ctx.listCounter.value;
  ctx.listCounter.value += 1;
  return n === 0 ? "items" : `items${n + 1}`;
}

function serializeStringArray(values: string[]): string {
  const safe = values.map((v) => JSON.stringify(v));
  return `[${safe.join(", ")}]`;
}

// --- Emit: template --------------------------------------------------------

function serializeAttrs(attrs: AttrPair[]): string {
  if (attrs.length === 0) return "";
  return (
    " " +
    attrs
      .map(([name, value]) =>
        value === null ? name : `${name}="${value}"`,
      )
      .join(" ")
  );
}

function serializeNode(node: AstNode, indent: string): string {
  if (node.type === "text") {
    return node.text;
  }
  if (node.type === "comment") {
    return `<!--${node.text}-->`;
  }
  const tag = node.tag;
  if (tag === IF_WRAPPER_TAG) {
    const expr = node.attrs.find(([k]) => k === "expr")?.[1] ?? "";
    const inner = serializeChildren(node.children, indent + "  ");
    return `@if (${expr}) {\n${inner}\n${indent}}`;
  }
  if (tag === "__for__") {
    const alias = node.attrs.find(([k]) => k === "alias")?.[1] ?? "item";
    const source = node.attrs.find(([k]) => k === "source")?.[1] ?? "items";
    const inner = serializeChildren(node.children, indent + "  ");
    return `@for (${alias} of ${source}; track $index) {\n${inner}\n${indent}}`;
  }

  const openAttrs = serializeAttrs(node.attrs);
  if (VOID_TAGS.has(tag) && node.children.length === 0) {
    return `<${tag}${openAttrs} />`;
  }
  if (node.children.length === 0) {
    return `<${tag}${openAttrs}></${tag}>`;
  }
  const childText = serializeChildren(node.children, indent + "  ");
  return `<${tag}${openAttrs}>\n${childText}\n${indent}</${tag}>`;
}

function serializeChildren(nodes: AstNode[], indent: string): string {
  return nodes
    .map((child) => indent + serializeNode(child, indent))
    .join("\n");
}

function serializeTemplate(nodes: AstNode[]): string {
  return nodes.map((n) => serializeNode(n, "")).join("\n");
}

// --- Emit: component TS ----------------------------------------------------

function toSelector(componentName: string): string {
  const kebab = componentName
    .replace(/^Generated/, "")
    .replace(/Component$/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase();
  const slug = kebab.length > 0 ? kebab : "generated";
  return `app-${slug}`;
}

function renderHeuristicsBanner(applied: Set<AppliedHeuristic>): string {
  if (applied.size === 0) {
    return "// angular-convert: no heuristics fired; output mirrors input structure.";
  }
  const sorted = Array.from(applied).sort();
  return `// angular-convert heuristics: ${sorted.join(", ")}`;
}

function renderFields(
  fieldOrder: string[],
  fields: Record<string, string>,
  useSignals: boolean,
): string {
  if (fieldOrder.length === 0) return "";
  const lines = fieldOrder.map((name) => {
    const value = fields[name];
    return useSignals
      ? `  ${name} = signal(${value});`
      : `  ${name} = ${value};`;
  });
  return lines.join("\n") + "\n";
}

function renderMethods(methods: Set<string>): string {
  if (methods.size === 0) return "";
  const lines = Array.from(methods)
    .sort()
    .map(
      (name) =>
        `  ${name}(_event?: Event): void {\n    // TODO: implement ${name} handler.\n  }`,
    );
  return lines.join("\n\n") + "\n";
}

function renderComponentTs(args: {
  componentName: string;
  selector: string;
  template: string;
  appliedHeuristics: Set<AppliedHeuristic>;
  fieldOrder: string[];
  fields: Record<string, string>;
  methods: Set<string>;
  useSignals: boolean;
  usesFormsModule: boolean;
}): { componentTs: string; imports: string[] } {
  const imports: string[] = ["@angular/core"];
  const coreImports = new Set<string>(["Component"]);
  if (args.useSignals) coreImports.add("signal");
  const coreImportLine = `import { ${Array.from(coreImports).join(", ")} } from '@angular/core';`;

  const extraImportLines: string[] = [];
  const componentImports: string[] = [];
  if (args.usesFormsModule) {
    extraImportLines.push(`import { FormsModule } from '@angular/forms';`);
    componentImports.push("FormsModule");
    imports.push("@angular/forms");
  }

  const banner = renderHeuristicsBanner(args.appliedHeuristics);
  const indentedTemplate = args.template
    .split("\n")
    .map((line) => (line.length === 0 ? "" : "    " + line))
    .join("\n");

  const fieldsBlock = renderFields(args.fieldOrder, args.fields, args.useSignals);
  const methodsBlock = renderMethods(args.methods);

  const classBody =
    fieldsBlock.length > 0 || methodsBlock.length > 0
      ? `\n${fieldsBlock}${fieldsBlock && methodsBlock ? "\n" : ""}${methodsBlock}`
      : "";

  const importsLine =
    componentImports.length > 0
      ? `\n  imports: [${componentImports.join(", ")}],`
      : "";

  const allImportLines = [coreImportLine, ...extraImportLines].join("\n");

  const componentTs = `${banner}
${allImportLines}

@Component({
  selector: '${args.selector}',
  standalone: true,${importsLine}
  template: \`
${indentedTemplate}
  \`,
})
export class ${args.componentName} {${classBody}}
`;

  return { componentTs, imports };
}

function computeFollowUps(ctx: TransformContext): string[] {
  const followUps: string[] = [];
  if (ctx.usesFormsModule) {
    followUps.push(
      "FormsModule is imported for [(ngModel)] bindings. For complex forms" +
        " prefer Reactive Forms (ReactiveFormsModule + FormGroup/FormControl)" +
        " and typed form validators.",
    );
  }
  if (ctx.reactiveFormHint) {
    followUps.push(
      "A <form> element was detected. Consider promoting this to a" +
        " ReactiveFormsModule FormGroup with typed controls and a submit" +
        " handler — that matches Angular 17+ conventions and unlocks" +
        " validators, dirty tracking, and typed values.",
    );
  }
  if (ctx.applied.has("list-to-for")) {
    followUps.push(
      "List-to-@for folded plain-text siblings into a single @for loop." +
        " Replace the literal string array with the typed source of truth" +
        " (signal, observable, or input) from your project before shipping.",
    );
  }
  return followUps;
}

// --- Public API ------------------------------------------------------------

export function convertHtmlToAngular(
  html: string,
  options: AngularConversionOptions = {},
): AngularConversionResult {
  const componentName = options.componentName || "GeneratedComponent";
  const useSignals = options.useSignals ?? false;
  const ctx = newContext();

  const nodes = parseHtml(html);
  const transformed = transformTree(nodes, ctx);
  const template = serializeTemplate(transformed);

  const { componentTs, imports } = renderComponentTs({
    componentName,
    selector: toSelector(componentName),
    template,
    appliedHeuristics: ctx.applied,
    fieldOrder: ctx.fieldOrder,
    fields: ctx.fields,
    methods: ctx.methods,
    useSignals,
    usesFormsModule: ctx.usesFormsModule,
  });

  return {
    template,
    componentTs,
    imports,
    followUps: computeFollowUps(ctx),
  };
}
